### ISSUE TITLE
comments?

### ISSUE THREAD

**Issue by omidfi** [gothinkster/koa-knex-realworld-example#1]
Hi, do you mind if I add comments to the code? 
Might help learners. 

If I find time of course :)

**Comment by SandeeshS** [comment]
Sure go ahead :+1:

**Comment by dimonnwc3** [comment]
great idea!
What do you think, if instead of just plain text format, we choose some kind of "standardized" format? like http://apidocjs.com/ or swagger based?
so the format will be defined from the beginning and will produce automatically some human readable docs docs as well

**Comment by omidfi** [comment]
Apidoxsjs looks nice. Howevwr the api spec seems to be well documented by realworld. i'm more concerned about the code itself. 

Have you seen sailsjs code? I meant comments like that.

**Comment by dimonnwc3** [comment]
I checked sailsjs code, and it's too much verbose in my opinion. As well real world repos like express and redux haven't comment like sails.
I think the better way is writing README docs with description how it works in general
