### ISSUE TITLE
Badly written "enviroinment" to be renamed

### ISSUE THREAD

**Issue by HackerGen** [gothinkster/koa-knex-realworld-example#13]
Hello, I just found that the word "enviroinment" is badly written in "default.yml" and "custom-environment-variables.yml" config files. I think that it should be renamed into "environment". 

Here are the concerned lines:

https://github.com/gothinkster/koa-knex-realworld-example/blob/db45c7329f6df029f08f9775432ea5164b74ffdd/config/default.yml#L7

https://github.com/gothinkster/koa-knex-realworld-example/blob/db45c7329f6df029f08f9775432ea5164b74ffdd/config/custom-environment-variables.yml#L7

https://github.com/gothinkster/koa-knex-realworld-example/blob/db45c7329f6df029f08f9775432ea5164b74ffdd/src/lib/logger.js#L24

**Comment by dimonnwc3** [comment]
@HackerGen Hi and thanks for that

typo needs to be fixes

I would appreciate a PR
