### ISSUE TITLE
POST /api/articles works fine on Postman but giving Unauthorized error while requesting from superagent

### ISSUE THREAD

**Issue by blackdeve** [gothinkster/koa-knex-realworld-example#8]
Here's my code:
```
import superagentPromise from 'superagent-promise';
import _superagent from 'superagent';

const superagent = superagentPromise(_superagent, global.Promise);
const API_ROOT = 'http://localhost:3000/api';

const Articles = {
    create: article =>
    superagent.post(`${API_ROOT}/articles`, { article })
      .set('Content-Type', 'application/json')
      .set('Authorization', `Token ${token}`)
      .set('X-Requested-With', 'XMLHttpRequest')
      .then(res => res.body)
}
```

This is error log of the Articles.create() function.
![issue](https://user-images.githubusercontent.com/36166782/44847524-1eb4ba80-ac97-11e8-8807-41f7b2b68cde.png)

Is there anyone who can fix this issue for me?
Thanks in advance!

**Comment by dimonnwc3** [comment]
`X-Requested-With` header is not allowed in CORS settings here: https://github.com/gothinkster/koa-knex-realworld-example/blob/master/src/config/index.js#L31

it works in postman, bcs. browser has CORS mechanism for better security https://en.wikipedia.org/wiki/Cross-origin_resource_sharing

why do you actually need this http header `X-Requested-With`?

**Comment by blackdeve** [comment]
If I remove `X-Requested-With` header, it gives `Unauthorized` error.

![issue](https://user-images.githubusercontent.com/36166782/44858750-099b5400-acb6-11e8-8343-f776c54f74ed.png)

Do you have any idea about this?
It works fine on Postman with the same `Authorization` header.

**Comment by dimonnwc3** [comment]
Looks like you use wrong token or bug in the application logic
needs more info

1. is it only on `POST /api/articles` endpoint or others too?
2. do you use the same host and token in postman and in the browser?
3. how do you get the token?

in your create function, I don't see token at all

**Comment by blackdeve** [comment]
1. Others also get errors
2. Yes,  I used same token in postman and in the browser
3. I get token by `POST /api/users/login`

**Comment by dimonnwc3** [comment]
can you also check in Chrome network tab that your actual XHR request contains the right header and the right value

**Comment by blackdeve** [comment]
yes, it has right header and values

![xhr](https://user-images.githubusercontent.com/36166782/44872417-d4542d80-acd8-11e8-8bc8-80041cd333d8.png)

**Comment by dimonnwc3** [comment]
works fine for me in chrome console
<img width="1440" alt="screen shot 2018-08-30 at 21 28 14" src="https://user-images.githubusercontent.com/6015849/44874676-3f334380-ac9c-11e8-82f5-891d5e9eb162.png">

make sure, that you receive and send the token to the same host

if don't work, create small reproducible example/repo to see what the problem, please

**Comment by blackdeve** [comment]
I tried with your code but it gives me error as well

Code :
![screen shot 2018-08-31 at 12 45 51 pm](https://user-images.githubusercontent.com/36166782/44890029-de4b5000-ad1b-11e8-8db8-1e715edeb124.png)

Error:
![screen shot 2018-08-31 at 12 47 11 pm](https://user-images.githubusercontent.com/36166782/44890070-06d34a00-ad1c-11e8-9afc-fa370349f77e.png)


Does this mean there is bug on my backend?

**Comment by dimonnwc3** [comment]
perhaps, this needs debugging to get the wrong place

**Comment by dimonnwc3** [comment]
I mean it's not clear where is the problem.
It could be both sides and needs debugging with some reproducible examples

**Comment by dimonnwc3** [comment]
closed due to inactivity
